advance_lpf_fields – ALaDyn
advance_lpf_fields Subroutine
45 statements
Source File
public subroutine advance_lpf_fields(ef, curr, ibd)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: ef(:,:,:,:)
real(kind=dp), intent(in) :: curr(:,:,:,:)
integer, intent(in) :: ibd
Calls
Called by
Contents
None
Call graph
advance_lpf_fields calls fill_ebfield_yzxbdsdata, rotb, ef_bds, bf_bds, field_xadvect, rote
fill_ebfield_yzxbdsdata calls exchange_bdx_data
rotb calls loc_yg, loc_zg
ef_bds calls loc_yg, loc_zgrid, loc_zg, loc_xg
bf_bds calls loc_yg, loc_zg, loc_xg
field_xadvect calls trid_der1
rote calls loc_yg, loc_zg
lpf2_evolve calls advance_lpf_fields
env_lpf2_evolve calls advance_lpf_fields
lp_run calls lpf2_evolve
env_run calls env_lpf2_evolve
env_cycle calls env_run
lp_cycle calls lp_run
aladyn calls env_cycle, lp_cycle