allreduce_dpreal – ALaDyn
allreduce_dpreal Subroutine
17 statements
Source File
public subroutine allreduce_dpreal(ib, rv_loc, rv, nt)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ib
real(kind=dp), intent(in) :: rv_loc(:)
real(kind=dp), intent(out) :: rv(:)
integer, intent(in) :: nt
Calls
Called by
Contents
None
Call graph
allreduce_dpreal calls mpi_allreduce
enb_bunch calls allreduce_dpreal, bunch_corr
fields_on_target calls allreduce_dpreal
laser_struct_data calls allreduce_dpreal
max_pmemory_check calls allreduce_dpreal
enb_ionz calls allreduce_dpreal, bunch_corr
enb_hgam calls allreduce_dpreal, bunch_corr
envelope_struct_data calls allreduce_dpreal
bunch_corr calls allreduce_dpreal
envar calls allreduce_dpreal, enb_bunch, envelope_struct_data
data_out calls envar
aladyn calls max_pmemory_check, env_cycle, lp_cycle
timing calls max_pmemory_check
env_cycle calls data_out, timing
lp_cycle calls data_out, timing