dump_data – ALaDyn
dump_data Subroutine
303 statements
Source File
public subroutine dump_data(it_loc, tloc)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: it_loc
real(kind=dp), intent(in) :: tloc
Calls
Contents
None
Call graph
dump_data calls wghpt, fluid_yz_profile, xpt, loc_npart, exchange_rdata_int, loc_ypt, intvec_distribute, fluid_x_profile, spec, ebf, up0, loc_wghyz, loc_zpt, env1, env, up
intvec_distribute calls mpi_bcast, mpi_send, mpi_recv