env_run – ALaDyn
env_run Subroutine
23 statements
Source File
public subroutine env_run(t_loc, iter_loc)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: t_loc
integer, intent(in) :: iter_loc
Calls
Called by
Contents
None
Call graph
env_run calls comoving_coordinate, env_lpf2_evolve, lp_window_xshift
comoving_coordinate calls cell_part_dist, particles_inject
env_lpf2_evolve calls env_amp_two_fields_prepare, update_adam_bash_fluid_variables, env_den_collect, fluid_curr_accumulate, spec, set_env_momentum_density_flux, advance_lpf_envelope, ion_min, enable_ionization, flux, curr_mpi_collect, jc, init_random_seed, env_two_fields_average, advance_lpf_fields, env_fields_average, atomic_number, ebfp, loc_npart, set_env_density, env_amp_prepare
lp_window_xshift calls cell_part_dist, part_numbers, particles_inject, fluid_left_xshift, fields_left_xshift
env_amp_two_fields_prepare calls env_grad
update_adam_bash_fluid_variables calls unit_charge, lorentz_fact, nc_fluid_density_momenta, fill_ebfield_yzxbdsdata, field_xyzbd
env_den_collect calls fill_curr_yzxbdsdata, den_zyxbd, loc_zg, loc_yg
fluid_curr_accumulate calls unit_charge, fill_ebfield_yzxbdsdata, field_xyzbd
advance_lpf_envelope calls fill_ebfield_yzxbdsdata, env_maxw_solve, env_bds, env_lpf_solve
cell_part_dist calls spec, ebfp, loc_npart, v_realloc
part_numbers calls loc_npart, intvec_distribute
curr_mpi_collect calls djc, jc_xyzbd, fill_curr_yzxbdsdata
particles_inject calls loc_npart, v_realloc, add_particles
advance_lpf_fields calls rotb, field_xadvect, fill_ebfield_yzxbdsdata, bf_bds, rote, ef_bds
env_fields_average calls env_grad
fluid_left_xshift calls exchange_bdx_data
fields_left_xshift calls exchange_bdx_data
env_amp_prepare calls env_grad
rotb calls loc_zg, loc_yg
field_xadvect calls trid_der1
nc_fluid_density_momenta calls loc_zg, loc_yg
fill_ebfield_yzxbdsdata calls exchange_bdx_data
bf_bds calls loc_zg, loc_yg, loc_xg
rote calls loc_zg, loc_yg
ef_bds calls loc_zg, loc_yg, loc_zgrid, loc_xg
add_particles calls init_random_seed, gasdev
env_maxw_solve calls potential_lapl
env_bds calls loc_zg, loc_yg
intvec_distribute calls mpi_send, mpi_bcast, mpi_recv
env_lpf_solve calls pp_lapl
fill_curr_yzxbdsdata calls exchange_bdx_data
pp_lapl calls loc_zg, loc_yg
env_cycle calls env_run
aladyn calls env_cycle