Env_cycle – ALaDyn
Env_cycle Subroutine
23 statements
Source File
subroutine Env_cycle()
Arguments
None
Calls
Called by
Contents
None
Call graph
env_cycle calls error_message, timing, part_numbers, data_out, beam_inject, env_run
timing calls part_numbers, max_pmemory_check, tot_num_part
part_numbers calls loc_npart, intvec_distribute
data_out calls create_timestep_folder, env_fields_out, fields_out, den_energy_out, fields_out_new, envar, fluid_den_mom_out, part_pdata_out, prl_den_energy_interp, env_two_fields_out
beam_inject calls bunch, mpi_beam_distribute, spec, ebf, p_alloc, ebfb, jc, initial_beam_fields, init_random_seed, fill_ebfield_yzxbdsdata, ebfp, pot, mpi_beam_ftgrid_distribute, loc_nbpart, lp_end, loc_npart, ebf_bunch, beam_data
env_run calls comoving_coordinate, lp_window_xshift, env_lpf2_evolve
max_pmemory_check calls allreduce_dpreal
mpi_beam_distribute calls bunch, ebfb, loc_nbpart
env_fields_out calls exchange_pdata
fields_out calls exchange_pdata, endian
den_energy_out calls exchange_pdata, endian
fields_out_new calls mpi_write_field, endian
envar calls loc_npart, enb_bunch, mass, envelope_struct_data, allreduce_dpreal
initial_beam_fields calls loc_zg, loc_yg
fill_ebfield_yzxbdsdata calls exchange_bdx_data
fluid_den_mom_out calls exchange_pdata, endian
mpi_beam_ftgrid_distribute calls bunch, ebfb, loc_nbpart
part_pdata_out calls loc_npart, intvec_distribute, endian, mpi_write_part
comoving_coordinate calls cell_part_dist, particles_inject
lp_window_xshift calls part_numbers, cell_part_dist, particles_inject, fluid_left_xshift, fields_left_xshift
intvec_distribute calls mpi_send, mpi_bcast, mpi_recv
tot_num_part calls loc_npart
env_lpf2_evolve calls spec, jc, init_random_seed, ebfp, loc_npart, env_amp_two_fields_prepare, update_adam_bash_fluid_variables, env_den_collect, fluid_curr_accumulate, set_env_momentum_density_flux, advance_lpf_envelope, ion_min, enable_ionization, flux, curr_mpi_collect, env_two_fields_average, advance_lpf_fields, env_fields_average, atomic_number, set_env_density, env_amp_prepare
prl_den_energy_interp calls spec, jc, loc_npart, den_zyxbd, env, mass, loc_zg, loc_yg
env_two_fields_out calls exchange_pdata
beam_data calls ebfb, unit_charge, exchange_2d_grdata
env_amp_two_fields_prepare calls env_grad
mpi_write_field calls mpi_file_set_view, mpi_file_close, mpi_file_open, mpi_file_write
update_adam_bash_fluid_variables calls fill_ebfield_yzxbdsdata, unit_charge, lorentz_fact, nc_fluid_density_momenta, field_xyzbd
env_den_collect calls loc_zg, loc_yg, fill_curr_yzxbdsdata, den_zyxbd
fluid_curr_accumulate calls fill_ebfield_yzxbdsdata, unit_charge, field_xyzbd
advance_lpf_envelope calls fill_ebfield_yzxbdsdata, env_maxw_solve, env_bds, env_lpf_solve
cell_part_dist calls spec, ebfp, loc_npart, v_realloc
curr_mpi_collect calls djc, jc_xyzbd, fill_curr_yzxbdsdata
enb_bunch calls loc_npart, allreduce_dpreal, bunch_corr
particles_inject calls loc_npart, v_realloc, add_particles
advance_lpf_fields calls fill_ebfield_yzxbdsdata, rotb, field_xadvect, bf_bds, rote, ef_bds
env_fields_average calls env_grad
envelope_struct_data calls allreduce_dpreal
fluid_left_xshift calls exchange_bdx_data
mpi_write_part calls mpi_file_set_view, mpi_file_close, mpi_file_open, mpi_file_write
allreduce_dpreal calls mpi_allreduce
fields_left_xshift calls exchange_bdx_data
env_amp_prepare calls env_grad
rotb calls loc_zg, loc_yg
field_xadvect calls trid_der1
bunch_corr calls allreduce_dpreal
nc_fluid_density_momenta calls loc_zg, loc_yg
bf_bds calls loc_zg, loc_yg, loc_xg
rote calls loc_zg, loc_yg
ef_bds calls loc_zg, loc_yg, loc_zgrid, loc_xg
add_particles calls init_random_seed, gasdev
env_maxw_solve calls potential_lapl
env_bds calls loc_zg, loc_yg
env_lpf_solve calls pp_lapl
fill_curr_yzxbdsdata calls exchange_bdx_data
pp_lapl calls loc_zg, loc_yg
aladyn calls env_cycle