Envar – ALaDyn
Envar Subroutine
201 statements
Source File
public subroutine Envar(nst)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nst
Calls
Called by
Contents
None
Call graph
envar calls enb_bunch, mass, allreduce_dpreal, envelope_struct_data, loc_npart
enb_bunch calls allreduce_dpreal, loc_npart, bunch_corr
allreduce_dpreal calls mpi_allreduce
envelope_struct_data calls allreduce_dpreal
bunch_corr calls allreduce_dpreal
data_out calls envar
env_cycle calls data_out
lp_cycle calls data_out
aladyn calls env_cycle, lp_cycle