gasdev – ALaDyn
gasdev Subroutine
23 statements
Source File
public subroutine gasdev(dev)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(out) :: dev
Called by
Contents
None
Call graph
add_particles calls gasdev
bunch_gen calls gasdev
pspecies_distribute calls gasdev
env_ionization_electrons_inject calls gasdev
ionization_electrons_inject calls gasdev
one_layer_nano_tubes calls gasdev
particles_inject calls add_particles
ionization_cycle calls env_ionization_electrons_inject, ionization_electrons_inject
part_distribute calls one_layer_nano_tubes
comoving_coordinate calls particles_inject
init calls part_distribute
lp_window_xshift calls particles_inject
lp_run calls comoving_coordinate, lp_window_xshift
start calls init
env_run calls comoving_coordinate, lp_window_xshift
aladyn calls start, lp_cycle, env_cycle
lp_cycle calls lp_run
env_cycle calls env_run