init – ALaDyn
init Subroutine
14 statements
Source File
public subroutine init()
Arguments
None
Calls
Called by
Contents
None
Call graph
init calls cp_pulse, set_envelope, part_distribute, lp_pulse
cp_pulse calls loc_xgrid, init_cp_fields, lp_in, lp_end, lpx
set_envelope calls z0_cent, init_gprof_envelope_field, lp_delay, y0_cent, loc_xgrid, lp_in, xc_loc, xf_loc, lp_end, lpx, init_envelope_field
part_distribute calls multi_layer_gas_target, preplasma_multisp, multi_layer_twosp_target, one_layer_nano_wires, multi_layer_threesp_target, one_layer_nano_tubes
lp_pulse calls z0_cent, lp_delay, y0_cent, loc_xgrid, init_lp_inc0_fields, lp_in, xc_loc, xf_loc, lp_end, lpx
multi_layer_gas_target calls loc_wghx, spec, p_alloc, wghpt, set_uniform_yz_distrib, mpi_x_part_distrib, xpt, loc_xpt
init_gprof_envelope_field calls loc_zgrid, loc_xg, loc_ygrid, loc_zg, loc_yg
preplasma_multisp calls loc_wghx, spec, p_alloc, wghpt, set_uniform_yz_distrib, xpt, loc_xpt
multi_layer_twosp_target calls loc_wghx, spec, p_alloc, wghpt, set_uniform_yz_distrib, xpt, loc_xpt
one_layer_nano_wires calls loc_wghx, spec, p_alloc, set_pgrid_ind, wghpt, loc_zpt, xpt, mpi_yz_part_distrib, zpt, loc_ypt, loc_xpt, loc_wghyz, ypt
init_cp_fields calls get_laser_fields_cp, loc_zgrid, get_plane_wave_cp, loc_xg, loc_ygrid, loc_zg, loc_yg
init_lp_inc0_fields calls get_laser_gprof_fields_lp, get_2dlaser_fields_lp, get_laser_fields_lp, loc_zgrid, loc_xg, loc_ygrid, loc_zg, get_2dlaser_gprof_fields_lp, loc_yg, get_plane_wave_lp
multi_layer_threesp_target calls loc_wghx, spec, p_alloc, wghpt, set_uniform_yz_distrib, xpt, loc_xpt
init_envelope_field calls loc_zgrid, loc_xg, loc_ygrid, loc_zg, loc_yg
one_layer_nano_tubes calls spec, p_alloc, wghpt, gasdev, loc_zpt, init_random_seed, xpt, mpi_yz_part_distrib, zpt, loc_ypt, loc_xpt, loc_wghyz, ypt
set_pgrid_ind calls zpt, ypt
set_uniform_yz_distrib calls set_pgrid_ind, loc_zpt, mpi_yz_part_distrib, zpt, loc_ypt, loc_wghyz, ypt
mpi_x_part_distrib calls loc_wghx, wghpt, xpt, loc_xpt
mpi_yz_part_distrib calls loc_zpt, zpt, loc_ypt, loc_wghyz, ypt
start calls init
aladyn calls start