invert_uniform_grid – ALaDyn
invert_uniform_grid Function
8 statements
Source File
private pure function invert_uniform_grid(yp_in, params) result(uniform)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: yp_in
type(str_params), intent(in) :: params
Return Value real(kind=dp)
Called by
Contents
None
Call graph
map2dy_part_sind calls invert_uniform_grid
map2dz_part_sind calls invert_uniform_grid
map3d_part_sind calls map2dy_part_sind, map2dz_part_sind
set_local_2d_positions calls map2dy_part_sind
set_env_density calls set_local_2d_positions, set_local_3d_positions
set_grid_charge calls set_local_2d_positions, set_local_3d_positions
set_local_3d_positions calls map3d_part_sind
set_part2d_hcell_acc calls set_local_2d_positions
esirkepov_2d_curr calls set_local_2d_positions
set_grid_charge_and_jx calls set_local_2d_positions, set_local_3d_positions
set_grid_den_energy calls set_local_2d_positions, set_local_3d_positions
set_grid_env_den_energy calls set_local_2d_positions, set_local_3d_positions
set_env_grad_interp calls set_local_2d_positions, set_local_3d_positions
set_ion_env_field calls set_local_2d_positions, set_local_3d_positions
set_env_acc calls set_local_2d_positions, set_local_3d_positions
set_ion_efield calls set_local_2d_positions, set_local_3d_positions
ncdef_2d_curr calls set_local_2d_positions
set_part3d_hcell_acc calls set_local_3d_positions
curr_accumulate calls esirkepov_2d_curr, ncdef_2d_curr, esirkepov_3d_curr, ncdef_3d_curr
esirkepov_3d_curr calls set_local_3d_positions
set_lpf_acc calls set_part2d_hcell_acc, set_part3d_hcell_acc
ncdef_3d_curr calls set_local_3d_positions