logical_dimension – ALaDyn
logical_dimension Function
13 statements
Source File
public pure function logical_dimension(kind_flag, N) result(log_dim)
Returns the logical dimension given the FFT Kind. To be generalized for other applications than FFTW_RODFT00 and FFTW_REDFT00
Arguments
Type Intent Optional Attributes Name
integer(kind=C_INTPTR_T), intent(in) :: kind_flag
integer, intent(in) :: N
Return Value integer
Called by
Contents
None
Call graph
ftw1d_sc calls logical_dimension
pftw3d_sc calls ftw1d_sc, pftw2d_sc
pftw2d_sc calls ftw1d_sc
fft_2d_psolv calls pftw2d_sc
fft_3d_psolv calls pftw3d_sc
set_wake_potential calls fft_2d_psolv