Lp_cycle – ALaDyn
Lp_cycle Subroutine
15 statements
Source File
subroutine Lp_cycle()
LP_CYCLE: collects the Laser-plasma dynamics evolved as a standard PIC.
Arguments
None
Calls
Called by
Contents
None
Call graph
lp_cycle calls lp_run, error_message, data_out, timing
lp_run calls lpf2_evolve, lp_window_xshift, comoving_coordinate
data_out calls create_timestep_folder, prl_den_energy_interp, fields_out, den_energy_out, fluid_den_mom_out, fields_out_new, part_pdata_out, env_fields_out, envar, env_two_fields_out
timing calls max_pmemory_check, part_numbers, tot_num_part
prl_den_energy_interp calls spec, den_zyxbd, jc, env, mass, loc_npart, loc_zg, loc_yg
lpf2_evolve calls update_adam_bash_fluid_variables, pfields_prepare, fluid_curr_accumulate, spec, ion_min, set_momentum_density_flux, jc, advance_lpf_fields, atomic_number, ebfp, loc_npart, init_random_seed
fields_out calls exchange_pdata, endian
lp_window_xshift calls part_numbers, cell_part_dist, particles_inject, fluid_left_xshift, fields_left_xshift
den_energy_out calls exchange_pdata, endian
max_pmemory_check calls allreduce_dpreal
fluid_den_mom_out calls exchange_pdata, endian
part_numbers calls loc_npart, intvec_distribute
fields_out_new calls mpi_write_field, endian
tot_num_part calls loc_npart
part_pdata_out calls endian, loc_npart, mpi_write_part, intvec_distribute
env_fields_out calls exchange_pdata
comoving_coordinate calls cell_part_dist, particles_inject
envar calls enb_bunch, mass, envelope_struct_data, loc_npart, allreduce_dpreal
env_two_fields_out calls exchange_pdata
mpi_write_field calls mpi_file_set_view, mpi_file_close, mpi_file_open, mpi_file_write
update_adam_bash_fluid_variables calls unit_charge, lorentz_fact, nc_fluid_density_momenta, fill_ebfield_yzxbdsdata, field_xyzbd
pfields_prepare calls fill_ebfield_yzxbdsdata, field_xyzbd
fluid_curr_accumulate calls unit_charge, fill_ebfield_yzxbdsdata, field_xyzbd
cell_part_dist calls spec, ebfp, loc_npart, v_realloc
enb_bunch calls loc_npart, allreduce_dpreal, bunch_corr
particles_inject calls loc_npart, v_realloc, add_particles
advance_lpf_fields calls rotb, field_xadvect, fill_ebfield_yzxbdsdata, bf_bds, ef_bds, rote
envelope_struct_data calls allreduce_dpreal
fluid_left_xshift calls exchange_bdx_data
mpi_write_part calls mpi_file_set_view, mpi_file_close, mpi_file_open, mpi_file_write
intvec_distribute calls mpi_send, mpi_bcast, mpi_recv
allreduce_dpreal calls mpi_allreduce
fields_left_xshift calls exchange_bdx_data
rotb calls loc_zg, loc_yg
field_xadvect calls trid_der1
bunch_corr calls allreduce_dpreal
nc_fluid_density_momenta calls loc_zg, loc_yg
fill_ebfield_yzxbdsdata calls exchange_bdx_data
bf_bds calls loc_zg, loc_yg, loc_xg
ef_bds calls loc_zg, loc_yg, loc_zgrid, loc_xg
rote calls loc_zg, loc_yg
add_particles calls gasdev, init_random_seed
aladyn calls lp_cycle