lp_pulse – ALaDyn
lp_pulse Subroutine
54 statements
Source File
public subroutine lp_pulse(lp_mod, part_in)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: lp_mod
real(kind=dp), intent(out) :: part_in
Calls
Called by
Contents
None
Call graph
lp_pulse calls lp_in, z0_cent, xc_loc, lpx, xf_loc, lp_end, init_lp_inc0_fields, lp_delay, y0_cent, loc_xgrid
init_lp_inc0_fields calls get_laser_gprof_fields_lp, get_2dlaser_gprof_fields_lp, get_laser_fields_lp, loc_yg, loc_ygrid, get_plane_wave_lp, loc_zgrid, get_2dlaser_fields_lp, loc_zg, loc_xg
init calls lp_pulse
start calls init
aladyn calls start