lp_run – ALaDyn
lp_run Subroutine
21 statements
Source File
public subroutine lp_run(t_loc, iter_loc)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: t_loc
integer, intent(in) :: iter_loc
Calls
Called by
Contents
None
Call graph
lp_run calls comoving_coordinate, lpf2_evolve, lp_window_xshift
comoving_coordinate calls particles_inject, cell_part_dist
lpf2_evolve calls advance_lpf_fields, ion_min, set_momentum_density_flux, update_adam_bash_fluid_variables, atomic_number, pfields_prepare, ebfp, fluid_curr_accumulate, jc, spec, loc_npart, init_random_seed
lp_window_xshift calls particles_inject, cell_part_dist, part_numbers, fields_left_xshift, fluid_left_xshift
particles_inject calls loc_npart, add_particles, v_realloc
advance_lpf_fields calls fill_ebfield_yzxbdsdata, rotb, ef_bds, bf_bds, field_xadvect, rote
cell_part_dist calls ebfp, spec, loc_npart, v_realloc
update_adam_bash_fluid_variables calls nc_fluid_density_momenta, fill_ebfield_yzxbdsdata, unit_charge, lorentz_fact, field_xyzbd
pfields_prepare calls fill_ebfield_yzxbdsdata, field_xyzbd
part_numbers calls loc_npart, intvec_distribute
fluid_curr_accumulate calls fill_ebfield_yzxbdsdata, unit_charge, field_xyzbd
fields_left_xshift calls exchange_bdx_data
fluid_left_xshift calls exchange_bdx_data
nc_fluid_density_momenta calls loc_yg, loc_zg
add_particles calls gasdev, init_random_seed
fill_ebfield_yzxbdsdata calls exchange_bdx_data
rotb calls loc_yg, loc_zg
intvec_distribute calls mpi_send, mpi_bcast, mpi_recv
ef_bds calls loc_yg, loc_zg, loc_zgrid, loc_xg
bf_bds calls loc_yg, loc_zg, loc_xg
field_xadvect calls trid_der1
rote calls loc_yg, loc_zg
lp_cycle calls lp_run
aladyn calls lp_cycle