lp_window_xshift – ALaDyn
lp_window_xshift Subroutine
62 statements
Source File
public subroutine lp_window_xshift(witr, init_iter)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: witr
integer, intent(in) :: init_iter
Calls
Called by
Contents
None
Call graph
lp_window_xshift calls particles_inject, cell_part_dist, part_numbers, fields_left_xshift, fluid_left_xshift
particles_inject calls add_particles, v_realloc, loc_npart
cell_part_dist calls v_realloc, ebfp, spec, loc_npart
part_numbers calls intvec_distribute, loc_npart
fields_left_xshift calls exchange_bdx_data
fluid_left_xshift calls exchange_bdx_data
add_particles calls gasdev, init_random_seed
intvec_distribute calls mpi_send, mpi_bcast, mpi_recv
lp_run calls lp_window_xshift
env_run calls lp_window_xshift
env_cycle calls env_run
lp_cycle calls lp_run
aladyn calls env_cycle, lp_cycle