lpf2_evolve – ALaDyn
lpf2_evolve Subroutine
47 statements
Source File
public subroutine lpf2_evolve(iter_loc)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iter_loc
Calls
Called by
Contents
None
Call graph
lpf2_evolve calls advance_lpf_fields, set_momentum_density_flux, ion_min, update_adam_bash_fluid_variables, atomic_number, pfields_prepare, ebfp, fluid_curr_accumulate, jc, spec, loc_npart, init_random_seed
advance_lpf_fields calls fill_ebfield_yzxbdsdata, rotb, ef_bds, bf_bds, field_xadvect, rote
update_adam_bash_fluid_variables calls nc_fluid_density_momenta, fill_ebfield_yzxbdsdata, unit_charge, lorentz_fact, field_xyzbd
pfields_prepare calls fill_ebfield_yzxbdsdata, field_xyzbd
fluid_curr_accumulate calls fill_ebfield_yzxbdsdata, unit_charge, field_xyzbd
nc_fluid_density_momenta calls loc_yg, loc_zg
fill_ebfield_yzxbdsdata calls exchange_bdx_data
rotb calls loc_yg, loc_zg
ef_bds calls loc_yg, loc_zgrid, loc_zg, loc_xg
bf_bds calls loc_yg, loc_zg, loc_xg
field_xadvect calls trid_der1
rote calls loc_yg, loc_zg
lp_run calls lpf2_evolve
lp_cycle calls lp_run
aladyn calls lp_cycle