mpi_yz_part_distrib – ALaDyn
mpi_yz_part_distrib Subroutine
46 statements
Source File
private subroutine mpi_yz_part_distrib(nc, ky2_in, kz2_in, nyc, nzc, ymt, zmt, whyz)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nc
integer, intent(in) :: ky2_in(:)
integer, intent(in) :: kz2_in(:)
integer, intent(in) :: nyc(:)
integer, intent(in) :: nzc(:)
real(kind=dp), intent(in) :: ymt
real(kind=dp), intent(in) :: zmt
real(kind=dp), intent(in) :: whyz(:,:,:)
Calls
Called by
Contents
None
Call graph
mpi_yz_part_distrib calls loc_ypt, loc_wghyz, loc_zpt, zpt, ypt
set_uniform_yz_distrib calls mpi_yz_part_distrib
one_layer_nano_wires calls mpi_yz_part_distrib
one_layer_nano_tubes calls mpi_yz_part_distrib
multi_layer_gas_target calls set_uniform_yz_distrib
part_distribute calls one_layer_nano_wires, one_layer_nano_tubes, multi_layer_gas_target, preplasma_multisp, multi_layer_twosp_target, multi_layer_threesp_target
preplasma_multisp calls set_uniform_yz_distrib
multi_layer_twosp_target calls set_uniform_yz_distrib
multi_layer_threesp_target calls set_uniform_yz_distrib
init calls part_distribute
start calls init
aladyn calls start