multi_layer_twosp_target – ALaDyn
multi_layer_twosp_target Subroutine
174 statements
Source File
private subroutine multi_layer_twosp_target(nyh_in, xf0)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nyh_in
real(kind=dp), intent(in) :: xf0
Calls
Called by
Contents
None
Call graph
multi_layer_twosp_target calls wghpt, spec, loc_wghx, set_uniform_yz_distrib, loc_xpt, xpt, p_alloc
set_uniform_yz_distrib calls set_pgrid_ind, loc_ypt, mpi_yz_part_distrib, loc_wghyz, loc_zpt, zpt, ypt
set_pgrid_ind calls zpt, ypt
mpi_yz_part_distrib calls loc_ypt, loc_wghyz, loc_zpt, zpt, ypt
part_distribute calls multi_layer_twosp_target
init calls part_distribute
start calls init
aladyn calls start