one_layer_nano_tubes – ALaDyn
one_layer_nano_tubes Subroutine
257 statements
Source File
private subroutine one_layer_nano_tubes(nyh_in, xf0)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nyh_in
real(kind=dp), intent(in) :: xf0
Calls
Called by
Contents
None
Call graph
one_layer_nano_tubes calls wghpt, gasdev, xpt, mpi_yz_part_distrib, loc_ypt, zpt, spec, loc_xpt, p_alloc, loc_wghyz, loc_zpt, init_random_seed, ypt
mpi_yz_part_distrib calls loc_ypt, zpt, loc_wghyz, loc_zpt, ypt
part_distribute calls one_layer_nano_tubes
init calls part_distribute
start calls init
aladyn calls start