particles_inject – ALaDyn
particles_inject Subroutine
60 statements
Source File
public subroutine particles_inject(xmx)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: xmx
Calls
Called by
Contents
None
Call graph
particles_inject calls v_realloc, loc_npart, add_particles
add_particles calls gasdev, init_random_seed
comoving_coordinate calls particles_inject
lp_window_xshift calls particles_inject
lp_run calls comoving_coordinate, lp_window_xshift
env_run calls comoving_coordinate, lp_window_xshift
env_cycle calls env_run
lp_cycle calls lp_run
aladyn calls env_cycle, lp_cycle