part_distribute – ALaDyn
part_distribute Subroutine
38 statements
Source File
public subroutine part_distribute(id, xf0)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: id
real(kind=dp), intent(in) :: xf0
Calls
Called by
Contents
None
Call graph
part_distribute calls multi_layer_gas_target, one_layer_nano_wires, preplasma_multisp, multi_layer_twosp_target, multi_layer_threesp_target, one_layer_nano_tubes
multi_layer_gas_target calls wghpt, xpt, loc_wghx, mpi_x_part_distrib, set_uniform_yz_distrib, spec, loc_xpt, p_alloc
one_layer_nano_wires calls wghpt, set_pgrid_ind, xpt, loc_wghx, mpi_yz_part_distrib, loc_ypt, spec, loc_xpt, p_alloc, loc_wghyz, loc_zpt, zpt, ypt
preplasma_multisp calls wghpt, xpt, loc_wghx, set_uniform_yz_distrib, spec, loc_xpt, p_alloc
multi_layer_twosp_target calls wghpt, xpt, loc_wghx, set_uniform_yz_distrib, spec, loc_xpt, p_alloc
multi_layer_threesp_target calls wghpt, xpt, loc_wghx, set_uniform_yz_distrib, spec, loc_xpt, p_alloc
one_layer_nano_tubes calls wghpt, gasdev, xpt, mpi_yz_part_distrib, loc_ypt, init_random_seed, spec, loc_xpt, p_alloc, loc_wghyz, loc_zpt, zpt, ypt
set_pgrid_ind calls zpt, ypt
mpi_yz_part_distrib calls loc_ypt, loc_wghyz, loc_zpt, zpt, ypt
mpi_x_part_distrib calls wghpt, xpt, loc_wghx, loc_xpt
set_uniform_yz_distrib calls set_pgrid_ind, mpi_yz_part_distrib, loc_ypt, loc_wghyz, loc_zpt, zpt, ypt
init calls part_distribute
start calls init
aladyn calls start