pftw2d_sc – ALaDyn
pftw2d_sc Subroutine
47 statements
Source File
public subroutine pftw2d_sc(w, n1, n2, n2_loc, n3, n3_loc, is, sym)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: w(:,:,:)
integer, intent(in) :: n1
integer, intent(in) :: n2
integer, intent(in) :: n2_loc
integer, intent(in) :: n3
integer, intent(in) :: n3_loc
integer, intent(in) :: is
integer, intent(in) :: sym
Calls
Called by
Contents
None
Call graph
pftw2d_sc calls swap_xz_3data_inv, ftw1d_sc, swap_xz_3data, swap_xy_3data_inv, swap_xy_3data
swap_xz_3data_inv calls zp_next, comm_col, zp_prev
ftw1d_sc calls fftw_execute_r2r, logical_dimension, determine_kind
swap_xz_3data calls zp_next, comm_col, zp_prev
swap_xy_3data_inv calls yp_prev, comm_col, yp_next
swap_xy_3data calls yp_prev, comm_col, yp_next
pftw3d_sc calls pftw2d_sc
fft_2d_psolv calls pftw2d_sc
set_wake_potential calls fft_2d_psolv
fft_3d_psolv calls pftw3d_sc