restart – ALaDyn
restart Subroutine
369 statements
Source File
public subroutine restart(it_loc, tloc)
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: it_loc
real(kind=dp), intent(out) :: tloc
Calls
Called by
Contents
None
Call graph
restart calls fluid_yz_profile, fluid_x_profile, spec, ebf, p_alloc, up0, wghpt, exchange_2d_grdata, loc_zpt, env1, env, real_bcast, xpt, loc_npart, vint_2d_bcast, up, exchange_1d_grdata, loc_ypt, intvec_distribute, vint_bcast, loc_wghyz
real_bcast calls mpi_bcast
intvec_distribute calls mpi_bcast, mpi_send, mpi_recv
vint_bcast calls mpi_bcast
start calls restart
aladyn calls start