set_env_grad_interp – ALaDyn
set_env_grad_interp Subroutine
96 statements
Source File
public subroutine set_env_grad_interp(av, sp_loc, pt, np, ndm)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: av(:,:,:,:)
type(species), intent(in) :: sp_loc
real(kind=dp), intent(inout) :: pt(:,:)
integer, intent(in) :: np
integer, intent(in) :: ndm
Calls
Contents
None
Call graph
set_env_grad_interp calls set_local_3d_positions, qqh_2d_spline, qqh_3d_spline, set_local_2d_positions
set_local_3d_positions calls map3d_part_sind
set_local_2d_positions calls map2dy_part_sind
map3d_part_sind calls map2dy_part_sind, map2dz_part_sind
map2dy_part_sind calls invert_stretched_grid, invert_uniform_grid
map2dz_part_sind calls invert_stretched_grid, invert_uniform_grid