set_wake_potential – ALaDyn
set_wake_potential Subroutine
21 statements
Source File
public subroutine set_wake_potential()
Arguments
None
Calls
Contents
None
Call graph
set_wake_potential calls fill_density_data, fft_2d_psolv, jc, spec, fill_curr_yzxbdsdata, loc_npart
fill_density_data calls z, y, x, loc_ygrid, loc_zgrid
fft_2d_psolv calls ftw_end, all_gather_dpreal, pftw2d_sc, pftw2d, mpi_ftw_alloc, ft_overset_grid, unif_to_str_field_interp, mpi_ftw_dalloc, ftw_init, mpi_yzft_ord, beam_2d_potential
fill_curr_yzxbdsdata calls exchange_bdx_data
pftw2d_sc calls swap_xz_3data_inv, ftw1d_sc, swap_xz_3data, swap_xy_3data_inv, swap_xy_3data
pftw2d calls swap_xz_3data_inv, ftw1d, swap_xz_3data, swap_xy_3data_inv, swap_xy_3data
ft_overset_grid calls yp_prev, zp_next, comm_col, yp_next, zp_prev
unif_to_str_field_interp calls loc_yft, loc_zft, loc_yg, zft_ind, loc_zg, yft_ind
swap_xz_3data_inv calls zp_next, comm_col, zp_prev
ftw1d_sc calls fftw_execute_r2r, logical_dimension, determine_kind
ftw1d calls fftw_execute_dft_r2c, fftw_execute_dft_c2r
swap_xz_3data calls zp_next, comm_col, zp_prev
swap_xy_3data_inv calls yp_prev, comm_col, yp_next
swap_xy_3data calls yp_prev, comm_col, yp_next