Start – ALaDyn
Start Subroutine
193 statements
Source File
public subroutine Start()
Start subroutine. It reads the input file, initializes the variables and allocates the needed arrays before to start the simulation.
Arguments
None
Calls
Called by
Contents
None
Call graph
start calls loc_yft, set_initial_param, start_parallel, set_field_param, write_read_nml, create_initial_folders, loc_yftgrid, set_output_grid, v_alloc, end_parallel, ion_min, mpi_barrier, float, set_ftgrid, init, set_loc_grid_param, atomic_number, set_fyzxgrid, loc_ygrid, yft_ind, mpi_buffer_alloc, read_main_input, mpi_loc_grid, restart, set_fxgrid, loc_yg, fluid_alloc
set_initial_param calls y, set_grid, z
set_ftgrid calls set_ftyzgrid, select_str_to_ft_grid
init calls cp_pulse, set_envelope, part_distribute, lp_pulse
read_main_input calls read_input_nml
restart calls fluid_yz_profile, fluid_x_profile, spec, ebf, p_alloc, up0, wghpt, exchange_2d_grdata, loc_zpt, env1, env, real_bcast, xpt, loc_npart, vint_2d_bcast, up, exchange_1d_grdata, loc_ypt, intvec_distribute, vint_bcast, loc_wghyz
cp_pulse calls loc_xgrid, init_cp_fields, lp_in, lp_end, lpx
real_bcast calls mpi_bcast
set_envelope calls z0_cent, init_gprof_envelope_field, lp_delay, y0_cent, loc_xgrid, lp_in, xc_loc, xf_loc, lp_end, lpx, init_envelope_field
read_input_nml calls consistency_check_number_of_particles_comp, consistency_check_grid
part_distribute calls multi_layer_gas_target, preplasma_multisp, multi_layer_twosp_target, one_layer_nano_wires, multi_layer_threesp_target, one_layer_nano_tubes
intvec_distribute calls mpi_send, mpi_recv, mpi_bcast
vint_bcast calls mpi_bcast
lp_pulse calls z0_cent, lp_delay, y0_cent, loc_xgrid, init_lp_inc0_fields, lp_in, xc_loc, xf_loc, lp_end, lpx
multi_layer_gas_target calls spec, p_alloc, wghpt, xpt, loc_wghx, set_uniform_yz_distrib, mpi_x_part_distrib, loc_xpt
consistency_check_number_of_particles_comp calls from_ppc_to_npx_npy_npz
init_gprof_envelope_field calls loc_ygrid, loc_yg, loc_zgrid, loc_xg, loc_zg
preplasma_multisp calls spec, p_alloc, wghpt, xpt, loc_wghx, set_uniform_yz_distrib, loc_xpt
multi_layer_twosp_target calls spec, p_alloc, wghpt, xpt, loc_wghx, set_uniform_yz_distrib, loc_xpt
one_layer_nano_wires calls spec, p_alloc, wghpt, loc_zpt, xpt, loc_ypt, loc_wghyz, loc_wghx, set_pgrid_ind, mpi_yz_part_distrib, zpt, loc_xpt, ypt
init_cp_fields calls loc_ygrid, loc_yg, get_laser_fields_cp, loc_zgrid, get_plane_wave_cp, loc_xg, loc_zg
init_lp_inc0_fields calls loc_ygrid, loc_yg, get_laser_gprof_fields_lp, get_2dlaser_fields_lp, get_laser_fields_lp, loc_zgrid, loc_xg, loc_zg, get_2dlaser_gprof_fields_lp, get_plane_wave_lp
multi_layer_threesp_target calls spec, p_alloc, wghpt, xpt, loc_wghx, set_uniform_yz_distrib, loc_xpt
init_envelope_field calls loc_ygrid, loc_yg, loc_zgrid, loc_xg, loc_zg
one_layer_nano_tubes calls spec, p_alloc, wghpt, loc_zpt, xpt, loc_ypt, loc_wghyz, gasdev, init_random_seed, mpi_yz_part_distrib, zpt, loc_xpt, ypt
set_pgrid_ind calls zpt, ypt
from_ppc_to_npx_npy_npz calls isprime
set_uniform_yz_distrib calls loc_zpt, loc_ypt, loc_wghyz, set_pgrid_ind, mpi_yz_part_distrib, zpt, ypt
mpi_x_part_distrib calls wghpt, xpt, loc_wghx, loc_xpt
mpi_yz_part_distrib calls loc_zpt, loc_ypt, loc_wghyz, zpt, ypt
aladyn calls start