update_adam_bash_fluid_variables – ALaDyn
update_adam_bash_fluid_variables Subroutine
104 statements
Source File
public subroutine update_adam_bash_fluid_variables(u, u0, flx, ef)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: u(:,:,:,:)
real(kind=dp), intent(inout) :: u0(:,:,:,:)
real(kind=dp), intent(inout) :: flx(:,:,:,:)
real(kind=dp), intent(inout) :: ef(:,:,:,:)
Calls
Called by
Contents
None
Call graph
update_adam_bash_fluid_variables calls fill_ebfield_yzxbdsdata, unit_charge, field_xyzbd, lorentz_fact, nc_fluid_density_momenta
fill_ebfield_yzxbdsdata calls exchange_bdx_data
nc_fluid_density_momenta calls loc_yg, loc_zg
lpf2_evolve calls update_adam_bash_fluid_variables
env_lpf2_evolve calls update_adam_bash_fluid_variables
lp_run calls lpf2_evolve
env_run calls env_lpf2_evolve
env_cycle calls env_run
lp_cycle calls lp_run
aladyn calls env_cycle, lp_cycle