fftw_execute_dft_c2r – ALaDyn
fftw_execute_dft_c2r Interface
512 statements
Source File
interface
Called by
public subroutine fftw_execute_dft_c2r(p, in, out) bind(C, name="0")
Arguments
Type Intent Optional Attributes Name
type(C_PTR), value :: p
complex(kind=C_DOUBLE_COMPLEX), intent(inout), dimension(*) :: in
real(kind=C_DOUBLE), intent(out), dimension(*) :: out
Call graph
ftw1d_st calls fftw_execute_dft_c2r
ftw1d calls fftw_execute_dft_c2r
pftw2d calls ftw1d
pftw3d calls ftw1d, pftw2d
fft_2d_psolv calls pftw2d
fft_3d_psolv calls pftw3d
set_wake_potential calls fft_2d_psolv