aladyn – ALaDyn
aladyn Program
168 statements
Source File
Uses
start_all
diag_part_and_fields
run_data_info
pic_out_util
pic_out
init_beam_part_distrib
pic_evolve
env_evolve
Calls
Contents
Subroutines
Lp_cycle Env_cycle data_out
Subroutines
subroutine Lp_cycle()
LP_CYCLE: collects the Laser-plasma dynamics evolved as a standard PIC.
Arguments
None
subroutine Env_cycle()
Arguments
None
subroutine data_out()
Arguments
None
Call graph
aladyn calls lp_cycle, max_pmemory_check, end_parallel, part_numbers, final_run_info, start, env_cycle, mpi_barrier, initial_run_info
lp_cycle calls data_out, lp_run, error_message, timing
max_pmemory_check calls allreduce_dpreal
part_numbers calls loc_npart, intvec_distribute
start calls end_parallel, mpi_barrier, loc_yft, set_initial_param, start_parallel, set_field_param, write_read_nml, create_initial_folders, loc_yftgrid, set_output_grid, v_alloc, ion_min, float, set_ftgrid, init, set_loc_grid_param, atomic_number, set_fyzxgrid, loc_ygrid, yft_ind, mpi_buffer_alloc, read_main_input, mpi_loc_grid, restart, set_fxgrid, loc_yg, fluid_alloc
env_cycle calls part_numbers, data_out, beam_inject, error_message, timing, env_run
set_initial_param calls y, set_grid, z
data_out calls create_timestep_folder, env_fields_out, fields_out, den_energy_out, fields_out_new, envar, fluid_den_mom_out, part_pdata_out, prl_den_energy_interp, env_two_fields_out
beam_inject calls loc_npart, bunch, mpi_beam_distribute, spec, ebf, p_alloc, ebfb, jc, initial_beam_fields, init_random_seed, fill_ebfield_yzxbdsdata, ebfp, pot, mpi_beam_ftgrid_distribute, loc_nbpart, lp_end, ebf_bunch, beam_data
set_ftgrid calls set_ftyzgrid, select_str_to_ft_grid
lp_run calls lpf2_evolve, comoving_coordinate, lp_window_xshift
init calls cp_pulse, set_envelope, part_distribute, lp_pulse
read_main_input calls read_input_nml
restart calls loc_npart, intvec_distribute, fluid_yz_profile, fluid_x_profile, spec, ebf, p_alloc, up0, wghpt, exchange_2d_grdata, loc_zpt, env1, env, real_bcast, xpt, vint_2d_bcast, up, loc_wghyz, exchange_1d_grdata, loc_ypt, vint_bcast
timing calls max_pmemory_check, part_numbers, tot_num_part
intvec_distribute calls mpi_send, mpi_bcast, mpi_recv
allreduce_dpreal calls mpi_allreduce
env_run calls comoving_coordinate, lp_window_xshift, env_lpf2_evolve
mpi_beam_distribute calls bunch, ebfb, loc_nbpart
env_fields_out calls exchange_pdata
fields_out calls exchange_pdata, endian
den_energy_out calls exchange_pdata, endian
fields_out_new calls mpi_write_field, endian
cp_pulse calls lp_end, loc_xgrid, init_cp_fields, lp_in, lpx
envar calls loc_npart, allreduce_dpreal, enb_bunch, mass, envelope_struct_data
initial_beam_fields calls loc_yg, loc_zg
real_bcast calls mpi_bcast
lpf2_evolve calls ion_min, atomic_number, loc_npart, spec, jc, ebfp, update_adam_bash_fluid_variables, pfields_prepare, fluid_curr_accumulate, set_momentum_density_flux, advance_lpf_fields, init_random_seed
fill_ebfield_yzxbdsdata calls exchange_bdx_data
set_envelope calls lp_end, z0_cent, init_gprof_envelope_field, lp_delay, y0_cent, loc_xgrid, lp_in, xc_loc, xf_loc, lpx, init_envelope_field
fluid_den_mom_out calls exchange_pdata, endian
read_input_nml calls consistency_check_number_of_particles_comp, consistency_check_grid
mpi_beam_ftgrid_distribute calls bunch, ebfb, loc_nbpart
part_pdata_out calls loc_npart, intvec_distribute, endian, mpi_write_part
comoving_coordinate calls cell_part_dist, particles_inject
lp_window_xshift calls part_numbers, cell_part_dist, particles_inject, fluid_left_xshift, fields_left_xshift
part_distribute calls multi_layer_gas_target, preplasma_multisp, multi_layer_twosp_target, one_layer_nano_wires, multi_layer_threesp_target, one_layer_nano_tubes
tot_num_part calls loc_npart
env_lpf2_evolve calls ion_min, atomic_number, loc_npart, spec, jc, init_random_seed, ebfp, env_amp_two_fields_prepare, update_adam_bash_fluid_variables, env_den_collect, fluid_curr_accumulate, set_env_momentum_density_flux, advance_lpf_envelope, enable_ionization, flux, curr_mpi_collect, env_two_fields_average, advance_lpf_fields, env_fields_average, set_env_density, env_amp_prepare
vint_bcast calls mpi_bcast
prl_den_energy_interp calls loc_npart, loc_yg, spec, jc, env, den_zyxbd, mass, loc_zg
env_two_fields_out calls exchange_pdata
beam_data calls ebfb, unit_charge, exchange_2d_grdata
lp_pulse calls lp_end, z0_cent, lp_delay, y0_cent, loc_xgrid, init_lp_inc0_fields, lp_in, xc_loc, xf_loc, lpx
multi_layer_gas_target calls spec, p_alloc, wghpt, xpt, loc_wghx, set_uniform_yz_distrib, mpi_x_part_distrib, loc_xpt
env_amp_two_fields_prepare calls env_grad
mpi_write_field calls mpi_file_set_view, mpi_file_close, mpi_file_open, mpi_file_write
update_adam_bash_fluid_variables calls fill_ebfield_yzxbdsdata, unit_charge, lorentz_fact, nc_fluid_density_momenta, field_xyzbd
consistency_check_number_of_particles_comp calls from_ppc_to_npx_npy_npz
pfields_prepare calls fill_ebfield_yzxbdsdata, field_xyzbd
env_den_collect calls loc_yg, loc_zg, fill_curr_yzxbdsdata, den_zyxbd
init_gprof_envelope_field calls loc_ygrid, loc_yg, loc_zg, loc_zgrid, loc_xg
preplasma_multisp calls spec, p_alloc, wghpt, xpt, loc_wghx, set_uniform_yz_distrib, loc_xpt
fluid_curr_accumulate calls fill_ebfield_yzxbdsdata, unit_charge, field_xyzbd
multi_layer_twosp_target calls spec, p_alloc, wghpt, xpt, loc_wghx, set_uniform_yz_distrib, loc_xpt
one_layer_nano_wires calls spec, p_alloc, wghpt, loc_zpt, xpt, loc_wghyz, loc_ypt, loc_wghx, set_pgrid_ind, ypt, mpi_yz_part_distrib, zpt, loc_xpt
init_cp_fields calls loc_ygrid, loc_yg, loc_zg, get_laser_fields_cp, loc_zgrid, get_plane_wave_cp, loc_xg
advance_lpf_envelope calls fill_ebfield_yzxbdsdata, env_lpf_solve, env_maxw_solve, env_bds
cell_part_dist calls loc_npart, spec, ebfp, v_realloc
curr_mpi_collect calls djc, jc_xyzbd, fill_curr_yzxbdsdata
init_lp_inc0_fields calls loc_ygrid, loc_yg, loc_zg, get_laser_gprof_fields_lp, get_2dlaser_fields_lp, get_laser_fields_lp, loc_zgrid, loc_xg, get_2dlaser_gprof_fields_lp, get_plane_wave_lp
multi_layer_threesp_target calls spec, p_alloc, wghpt, xpt, loc_wghx, set_uniform_yz_distrib, loc_xpt
enb_bunch calls loc_npart, allreduce_dpreal, bunch_corr
particles_inject calls loc_npart, v_realloc, add_particles
advance_lpf_fields calls fill_ebfield_yzxbdsdata, rotb, field_xadvect, bf_bds, rote, ef_bds
env_fields_average calls env_grad
envelope_struct_data calls allreduce_dpreal
fluid_left_xshift calls exchange_bdx_data
mpi_write_part calls mpi_file_set_view, mpi_file_close, mpi_file_open, mpi_file_write
fields_left_xshift calls exchange_bdx_data
init_envelope_field calls loc_ygrid, loc_yg, loc_zg, loc_zgrid, loc_xg
env_amp_prepare calls env_grad
one_layer_nano_tubes calls spec, p_alloc, wghpt, loc_zpt, init_random_seed, xpt, loc_wghyz, loc_ypt, gasdev, ypt, mpi_yz_part_distrib, zpt, loc_xpt
set_pgrid_ind calls ypt, zpt
from_ppc_to_npx_npy_npz calls isprime
rotb calls loc_yg, loc_zg
field_xadvect calls trid_der1
bunch_corr calls allreduce_dpreal
set_uniform_yz_distrib calls loc_zpt, loc_wghyz, loc_ypt, set_pgrid_ind, ypt, mpi_yz_part_distrib, zpt
env_lpf_solve calls pp_lapl
nc_fluid_density_momenta calls loc_yg, loc_zg
mpi_x_part_distrib calls wghpt, xpt, loc_wghx, loc_xpt
bf_bds calls loc_yg, loc_zg, loc_xg
mpi_yz_part_distrib calls loc_zpt, loc_wghyz, loc_ypt, ypt, zpt
rote calls loc_yg, loc_zg
ef_bds calls loc_yg, loc_zg, loc_zgrid, loc_xg
add_particles calls init_random_seed, gasdev
env_maxw_solve calls potential_lapl
env_bds calls loc_yg, loc_zg
fill_curr_yzxbdsdata calls exchange_bdx_data
pp_lapl calls loc_yg, loc_zg